name: Build and Publish Docker
on:
	push:
		brancher:
		- main
jobs:
	test:
		runs-on: ubuntu-latest
		steps:
		- name: checkout
		  uses: actions/checkou@v2
		- name: Install dependencies
		  run: npm install
		- name: Run unit tests
		  run: npm test
		  env:
			SQLITE_DB_LOCATION: /tmp/todo.db

